language: ruby
rvm:
  - 2.7.0
gemfile:
  - Gemfile
  - gemfiles/nokogiri-1.5.gemfile
before_install:
  - gem update bundler
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: ree
      gemfile: Gemfile
    - rvm: jruby-1.7.27
      gemfile: gemfiles/nokogiri-1.5.gemfile
    - rvm: jruby-9.1.17.0
      gemfile: gemfiles/nokogiri-1.5.gemfile
    - rvm: jruby-9.2.7.0
      gemfile: gemfiles/nokogiri-1.5.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/nokogiri-1.5.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/nokogiri-1.5.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/nokogiri-1.5.gemfile
    - rvm: 2.4.6
      gemfile: gemfiles/nokogiri-1.5.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/nokogiri-1.5.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/nokogiri-1.5.gemfile
env:
  - JRUBY_OPTS="--debug"
